repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.16 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: terraform-validate
    - id: terraform-fmt
repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"             # e.g. "v0.11.2"
    hooks:
      - id: terraform-docs-go
        args: ["--output-file", "README.md", "./example"]  # e.g. ["--output-file", "README.md", "./mymodule/path"]
